// Damage upload session model (Phase 6.4 Unit 1). `_id` is the crypto-random
// UUID generated by utils/damageUpload.js#generateUploadSessionId - not a
// MongoDB ObjectId - since that same value already serves as the public
// uploadSessionId, the removal-endpoint imageId, and the unguessable
// segment of the storage key (see controllers/damageUploadController.js).
// No Firebase credentials, tokens, or signed URLs are ever persisted here.

class DamageUploadSessionModel {
    constructor(collection) {
        this.collection = collection;
    }

    async create({ id, requestId, ownerEmail, storageKey, mimeType, declaredSize, expiresAt }, options = {}) {
        const doc = {
            _id: id,
            requestId,
            ownerEmail,
            storageKey,
            mimeType,
            declaredSize,
            status: 'pending',
            expiresAt,
            createdAt: new Date(),
            finalizedAt: null,
            cancelledAt: null
        };
        const insertOptions = {};
        if (options.session) insertOptions.session = options.session;
        await this.collection.insertOne(doc, insertOptions);
        return doc;
    }

    async findById(id, options = {}) {
        const findOptions = {};
        if (options.session) findOptions.session = options.session;
        return await this.collection.findOne({ _id: id }, findOptions);
    }

    // Atomic guard: only a session that is still pending/uploaded, not
    // expired, and tied to the exact request/owner/storageKey it was
    // created for can transition to finalized - every field the caller
    // already verified is re-asserted here as part of the update filter
    // itself (mirrors the "guard on every field read, not just the field
    // being changed" pattern established in Phase 6.3 Unit 6), so a
    // transaction retry or a racing second finalize call can never
    // silently finalize against a stale or mismatched session.
    async markFinalized({ id, requestId, ownerEmail, storageKey, now, session }) {
        const filter = {
            _id: id,
            requestId,
            ownerEmail,
            storageKey,
            status: { $in: ['pending', 'uploaded'] },
            expiresAt: { $gt: now }
        };
        return await this.collection.updateOne(
            filter,
            { $set: { status: 'finalized', finalizedAt: now } },
            { session }
        );
    }

    async markCancelled(id, { session } = {}) {
        return await this.collection.updateOne(
            { _id: id, status: { $in: ['pending', 'uploaded'] } },
            { $set: { status: 'cancelled', cancelledAt: new Date() } },
            { session }
        );
    }
}

module.exports = DamageUploadSessionModel;
